import express, { Router } from "express";
import chatRouter from "./chat";
import userRouter from "./user";
import authRouter from "./auth";

const router: Router = express.Router();

// Health check route
router.get("/health", (_req, res) => {
  res.status(200).json({
    success: true,
    message: "Server is running!",
    timestamp: new Date().toISOString(),
  });
});

/*
 * Chat / conversation routes
 *
 * NOTE:
 * - A chat is a container
 * - Messages (user + assistant) are append-only
 * - Assistant responses are generated by backend
 */

/*
 * 1. Send a user message to a chat and receive assistant response
 *    route   : /chat/:userId/conversations/:chatId/messages
 *    method  : POST
 *
 *    eg:
 *    - user sends a message to an existing chat
 *    - backend saves user message
 *    - backend generates assistant response
 *    - backend saves assistant response
 *
 *    pass    : [ content ]
 *    return  : [ role: "assistant", content, timestamp ]
 */

/*
 * 2. Get all conversations (chat summaries) for a user
 *    route   : /chat/:userId/conversations
 *    method  : GET
 *
 *    eg:
 *    - fetch list of chats for a user
 *
 *    return  : [
 *      { chatId, name, createdAt, updatedAt }
 *    ]
 */

/*
 * 3. Get a specific conversation with full message history
 *    route   : /chat/:userId/conversations/:chatId
 *    method  : GET
 *
 *    eg:
 *    - fetch complete conversation for a chat
 *
 *    return  : {
 *      chatId,
 *      name,
 *      messages: [ { role, content, timestamp } ]
 *    }
 */

/*
 * 4. Create a new conversation for a user
 *    route   : /chat/:userId/conversations
 *    method  : POST
 *
 *    eg:
 *    - create an empty chat or a chat with first user message
 *
 *    pass    : [ name?, content? ]
 *    return  : { chatId, name, createdAt }
 */

/*
 * 5. Delete a conversation for a user
 *    route   : /chat/:userId/conversations/:chatId
 *    method  : DELETE
 *
 *    eg:
 *    - permanently delete a chat and its messages
 *
 *    pass    : [ chatId ]
 *    return  : success message
 */

router.use("/chat", chatRouter);

/*
 * User metadata routes
 *
 * Scope:
 * - All routes are scoped to a specific user (:userId)
 * - Metadata is owned by the user and not shared across users
 */

/*
 * API Keys management
 *
 * 1. Get all API keys for a user
 *    route  : /users/:userId/meta/api-keys
 *    method : GET
 *
 * 2. Create a new API key for a user
 *    route  : /users/:userId/meta/api-keys
 *    method : POST
 *
 * 3. Update an existing API key by ID
 *    route  : /users/:userId/meta/api-keys/:apiKeyId
 *    method : PUT
 *
 * 4. Delete an API key by ID
 *    route  : /users/:userId/meta/api-keys/:apiKeyId
 *    method : DELETE
 */

/*
 * Instructions (system / prompt configuration) management
 *
 * 5. Get instructions by ID
 *    route  : /users/:userId/meta/instructions/:instructionId
 *    method : GET
 *
 * 6. Create new instructions for a user
 *    route  : /users/:userId/meta/instructions
 *    method : POST
 *
 * 7. Update existing instructions by ID
 *    route  : /users/:userId/meta/instructions/:instructionId
 *    method : PUT
 *
 * 8. Delete instructions by ID
 *    route  : /users/:userId/meta/instructions/:instructionId
 *    method : DELETE
 */

/*
 * User management routes
 *
 * Scope:
 * - Users represent logical ownership of chats, API keys, and instructions
 * - Authentication may be added later; userId is the primary identifier
 */

/*
 * 1. Create a new user
 *    route  : /users
 *    method : POST
 *
 *    eg:
 *    - create a new user record (anonymous or registered)
 */

/*
 * 2. Get a user by ID
 *    route  : /users/:userId
 *    method : GET
 *
 *    eg:
 *    - fetch user profile and basic metadata
 */

/*
 * 3. Update a user by ID
 *    route  : /users/:userId
 *    method : PUT
 *
 *    eg:
 *    - update user profile information
 */

/*
 * 4. Delete a user by ID
 *    route  : /users/:userId
 *    method : DELETE
 *
 *    eg:
 *    - permanently delete a user and all owned resources
 */
router.use("/users", userRouter);
/*
 * Authentication / Auth routes
 *
 * Scope:
 * - Handle user login, registration, logout, and session management
 * - Can be used alongside user management routes
 * - Tokens (JWT) or sessions identify the currently logged-in user
 */

/*
 * 1. Register a new user
 *    route  : /auth/register
 *    method : POST
 *
 *    eg:
 *    - create a new user with email and password
 *    - returns JWT token for authentication
 */

/*
 * 2. Login user
 *    route  : /auth/login
 *    method : POST
 *
 *    eg:
 *    - user provides email and password
 *    - backend verifies credentials
 *    - returns JWT token for authenticated requests
 */

/*
 * 3. Logout user
 *    route  : /auth/logout
 *    method : POST
 *
 *    eg:
 *    - invalidate current session or JWT refresh token
 *    - backend clears server-side session if applicable
 */

/*
 * 4. Get current authenticated user info
 *    route  : /auth/me
 *    method : GET
 *
 *    eg:
 *    - fetch profile and metadata of the logged-in user
 *    - uses token/session to identify the user
 */

/*
 * 5. Refresh authentication token
 *    route  : /auth/refresh
 *    method : POST
 *
 *    eg:
 *    - issue new JWT token using a refresh token
 *    - extends session without re-login
 */

router.use("/auth", authRouter);
export default router;
